### ISSUE TITLE
yml error: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wouterkroes** [mirabeau-nl/frontend-boilerplate#79]
When having invalid yml I get a `RangeError: Maximum call stack size exceeded`

Example of this invalid yml file:

```yml
title: testing
description: description details
demo: | {}
implementation: implementation details
```
